name: Build LaTeX PDF

on:
  push:
    branches: [main]
    paths:
      - "**.tex"
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build PDF (draft mode)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

          # Pass draft option to skip textbook PDF inclusion
          args: -pdf -interaction=nonstopmode -file-line-error
          pre_compile: |
            echo "\PassOptionsToClass{draft}{article}" > draft-preamble.tex
            cat main.tex >> draft-preamble.tex
            mv draft-preamble.tex main.tex

      - name: Push to build branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan build
          git rm -rf .
          git add -f main.pdf
          git commit -m "Latest build"
          git push origin HEAD:build --force
          git checkout -f main
          git branch -D build
